### PR TITLE
Fix a logic to get the latest release version

### LINKED ISSUE #10: Fix a logic to get the latest release version
On April 26 2021, there were terraform releases. But tfupdate release latest command returns the latest release depending on timestamp. 

```
$ tfupdate release latest hashicorp/terraform
0.11.15
```

although the latest version is `0.15.1`.

### PR DESCRIPTION
**Pull request by sharu1204**
## Description

- Avoid downgrading PR
- Bump version to 1.0.0

## Notes

Resolves #10 
Will release `v1.0.0` after merging the PR.

### CODE REVIEW

**Review by michaelaw320 — APPROVED** [review]

File: entrypoint.sh [hunk 1]
```diff
@@ -9,7 +9,7 @@ set -e
 function run_tfupdate {
   case ${INPUT_RESOURCE} in
     terraform)
-      VERSION=$(tfupdate release latest hashicorp/terraform)
+      VERSION=$(tfupdate release list hashicorp/terraform| grep -v ".*-rc[0-9]$"| sort -r| head -1)
```
Comment (taizo) [inline entrypoint.sh:12]: Sorry, maybe this should be okay for now, but `sort -r -n` would be better if we do numeric sorting. 🤔

Comment (taizo) [reply entrypoint.sh:12]: I'm sorry. `-n` doesn't work in some cases. please ignore 🙇🏼‍♂️ 

```
echo "0.12.17
0.12.18
0.12.19
0.12.20
0.12.21
0.1.30
0.12.5" | grep -v ".*-rc[0-9]$"| sort -r -n

0.12.5
0.12.21
0.12.20
0.12.19
0.12.18
0.12.17
0.1.30
```

Comment (taizo) [reply entrypoint.sh:12]: Seems `sort --version-sort -r` works.
